config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users
  resources :notes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = get_notes_call.data
  end

  def show
    @note = get_notes_by_id_call(id: params[:id]).data
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = get_users_call.data
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/_navigation.html.slim
nav.top-bar data-topbar=""
  .top-bar-right
    ul.menu
      li
        = link_to 'Users', users_path
      li
        = link_to 'Notes', notes_path

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Consumer"

    = stylesheet_link_tag "application"
    = csrf_meta_tag

  body

    header
      = render 'layouts/navigation'

    br

    == yield

    = javascript_include_tag "application"

app/views/notes/index.html.slim
.row
  .large-8.columns.large-centered
    table
      caption Notes
      thead
        tr
          th width="50%" Title
          th Content
      tbody
        - @notes.each do |note|
          tr
            td
              = link_to note.title, note_path(note.id)
            td= truncate note.content, length: 100

app/views/notes/show.html.slim
.row
  .large-8.columns.large-centered
    table
      caption Note ##{@note.id}
      thead
        tr
          th width="100" Title
          th width="300" Content
      tbody
        tr
          td= @note.title
          td= @note.content

app/views/users/index.html.slim
.row
  .large-8.columns.large-centered
    table
      caption USERS
      thead
        tr
          th width="50%" First name
          th Last name
      tbody
        - @users.each do |user|
          tr
            td
              = link_to user.first_name, user_path(user.id)
            td= truncate user.last_name, length: 100
      tfoot
        tr
          td Average age
          td
            = @users.map(&:age).sum / @users.map(&:age).size

app/views/users/show.html.slim
.row
  .large-8.columns.large-centered
    table
      caption User ##{@user.id}
      thead
        tr
          th width="100" First name
          th width="300" Last name
      tbody
        tr
          td= @user.first_name
          td= @user.last_name